# Generated by Django 4.2.11 on 2024-05-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
