# Generated by Django 4.2.11 on 2024-05-01 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0005_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like_users',
            field=models.ManyToManyField(related_name='like_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
